# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IPFC_Import.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportMenu(object):
    def setupUi(self, ImportMenu):
        ImportMenu.setObjectName("ImportMenu")
        ImportMenu.resize(380, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ImportMenu.sizePolicy().hasHeightForWidth())
        ImportMenu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        ImportMenu.setFont(font)
        ImportMenu.setStyleSheet("#ImportMenu { border-image: url(split_grey_background.jpg) 0 0 0 0 stretch stretch;}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ImportMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonBack = QtWidgets.QPushButton(ImportMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBack.sizePolicy().hasHeightForWidth())
        self.pushButtonBack.setSizePolicy(sizePolicy)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setAutoDefault(False)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.verticalLayout.addWidget(self.pushButtonBack)
        self.label = QtWidgets.QLabel(ImportMenu)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listFiles = QtWidgets.QListWidget(ImportMenu)
        self.listFiles.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listFiles.sizePolicy().hasHeightForWidth())
        self.listFiles.setSizePolicy(sizePolicy)
        self.listFiles.setMinimumSize(QtCore.QSize(0, 0))
        self.listFiles.setMaximumSize(QtCore.QSize(16777215, 12341234))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.listFiles.setFont(font)
        self.listFiles.setAlternatingRowColors(True)
        self.listFiles.setProperty("isWrapping", True)
        self.listFiles.setWordWrap(True)
        self.listFiles.setObjectName("listFiles")
        self.verticalLayout.addWidget(self.listFiles)
        self.label_2 = QtWidgets.QLabel(ImportMenu)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listDeckLibrary = QtWidgets.QListWidget(ImportMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listDeckLibrary.sizePolicy().hasHeightForWidth())
        self.listDeckLibrary.setSizePolicy(sizePolicy)
        self.listDeckLibrary.setMinimumSize(QtCore.QSize(0, 100))
        self.listDeckLibrary.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listDeckLibrary.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.listDeckLibrary.setFont(font)
        self.listDeckLibrary.setAlternatingRowColors(True)
        self.listDeckLibrary.setProperty("isWrapping", True)
        self.listDeckLibrary.setWordWrap(True)
        self.listDeckLibrary.setObjectName("listDeckLibrary")
        self.verticalLayout.addWidget(self.listDeckLibrary)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonImport = QtWidgets.QPushButton(ImportMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonImport.sizePolicy().hasHeightForWidth())
        self.pushButtonImport.setSizePolicy(sizePolicy)
        self.pushButtonImport.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonImport.setFont(font)
        self.pushButtonImport.setAutoDefault(False)
        self.pushButtonImport.setObjectName("pushButtonImport")
        self.horizontalLayout_2.addWidget(self.pushButtonImport)
        self.pushButtonExport = QtWidgets.QPushButton(ImportMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonExport.sizePolicy().hasHeightForWidth())
        self.pushButtonExport.setSizePolicy(sizePolicy)
        self.pushButtonExport.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonExport.setFont(font)
        self.pushButtonExport.setAutoDefault(False)
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.horizontalLayout_2.addWidget(self.pushButtonExport)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ImportMenu)
        QtCore.QMetaObject.connectSlotsByName(ImportMenu)

    def retranslateUi(self, ImportMenu):
        _translate = QtCore.QCoreApplication.translate
        ImportMenu.setWindowTitle(_translate("ImportMenu", "Inter Planetary Flash Cards"))
        self.pushButtonBack.setText(_translate("ImportMenu", "Back"))
        self.label.setText(_translate("ImportMenu", "Convert a file from the \"to_convert\" folder:"))
        self.label_2.setText(_translate("ImportMenu", "Decks already in deck library:"))
        self.pushButtonImport.setText(_translate("ImportMenu", "Import / convert"))
        self.pushButtonExport.setText(_translate("ImportMenu", "Export"))
