# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IPFC_Signup.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Signup(object):
    def setupUi(self, Signup):
        Signup.setObjectName("Signup")
        Signup.resize(380, 480)
        Signup.setStyleSheet("#Signup { border-image: url(split_grey_background.jpg) 0 0 0 0 stretch stretch;}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Signup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelWelcome = QtWidgets.QLabel(Signup)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.labelWelcome.setFont(font)
        self.labelWelcome.setObjectName("labelWelcome")
        self.verticalLayout.addWidget(self.labelWelcome)
        self.labelTitle = QtWidgets.QLabel(Signup)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        font.setPointSize(20)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 35, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButtonPinata = QtWidgets.QPushButton(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPinata.sizePolicy().hasHeightForWidth())
        self.pushButtonPinata.setSizePolicy(sizePolicy)
        self.pushButtonPinata.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonPinata.setFont(font)
        self.pushButtonPinata.setAutoDefault(False)
        self.pushButtonPinata.setObjectName("pushButtonPinata")
        self.horizontalLayout.addWidget(self.pushButtonPinata)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.labelEmail = QtWidgets.QLabel(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEmail.sizePolicy().hasHeightForWidth())
        self.labelEmail.setSizePolicy(sizePolicy)
        self.labelEmail.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.labelEmail.setFont(font)
        self.labelEmail.setAutoFillBackground(False)
        self.labelEmail.setScaledContents(False)
        self.labelEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelEmail.setIndent(0)
        self.labelEmail.setObjectName("labelEmail")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelEmail)
        self.lineEditEmail = QtWidgets.QLineEdit(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEmail.sizePolicy().hasHeightForWidth())
        self.lineEditEmail.setSizePolicy(sizePolicy)
        self.lineEditEmail.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditEmail)
        self.labelPassword = QtWidgets.QLabel(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPassword.sizePolicy().hasHeightForWidth())
        self.labelPassword.setSizePolicy(sizePolicy)
        self.labelPassword.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.labelPassword.setFont(font)
        self.labelPassword.setAutoFillBackground(False)
        self.labelPassword.setScaledContents(False)
        self.labelPassword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPassword.setIndent(0)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPassword.sizePolicy().hasHeightForWidth())
        self.lineEditPassword.setSizePolicy(sizePolicy)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditPassword)
        self.labelRepeatPassword = QtWidgets.QLabel(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRepeatPassword.sizePolicy().hasHeightForWidth())
        self.labelRepeatPassword.setSizePolicy(sizePolicy)
        self.labelRepeatPassword.setObjectName("labelRepeatPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelRepeatPassword)
        self.lineEditRepeatPassword = QtWidgets.QLineEdit(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRepeatPassword.sizePolicy().hasHeightForWidth())
        self.lineEditRepeatPassword.setSizePolicy(sizePolicy)
        self.lineEditRepeatPassword.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEditRepeatPassword.setObjectName("lineEditRepeatPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditRepeatPassword)
        self.labelPinataAPI = QtWidgets.QLabel(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPinataAPI.sizePolicy().hasHeightForWidth())
        self.labelPinataAPI.setSizePolicy(sizePolicy)
        self.labelPinataAPI.setMinimumSize(QtCore.QSize(0, 30))
        self.labelPinataAPI.setScaledContents(True)
        self.labelPinataAPI.setWordWrap(True)
        self.labelPinataAPI.setObjectName("labelPinataAPI")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelPinataAPI)
        self.lineEditPinataAPI = QtWidgets.QLineEdit(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPinataAPI.sizePolicy().hasHeightForWidth())
        self.lineEditPinataAPI.setSizePolicy(sizePolicy)
        self.lineEditPinataAPI.setObjectName("lineEditPinataAPI")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditPinataAPI)
        self.labelPinataKey = QtWidgets.QLabel(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPinataKey.sizePolicy().hasHeightForWidth())
        self.labelPinataKey.setSizePolicy(sizePolicy)
        self.labelPinataKey.setObjectName("labelPinataKey")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelPinataKey)
        self.lineEditPinataKey = QtWidgets.QLineEdit(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPinataKey.sizePolicy().hasHeightForWidth())
        self.lineEditPinataKey.setSizePolicy(sizePolicy)
        self.lineEditPinataKey.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEditPinataKey.setObjectName("lineEditPinataKey")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditPinataKey)
        self.labelResponse = QtWidgets.QLabel(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelResponse.sizePolicy().hasHeightForWidth())
        self.labelResponse.setSizePolicy(sizePolicy)
        self.labelResponse.setMinimumSize(QtCore.QSize(0, 40))
        self.labelResponse.setText("")
        self.labelResponse.setScaledContents(True)
        self.labelResponse.setWordWrap(True)
        self.labelResponse.setObjectName("labelResponse")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelResponse)
        self.pushButtonSignup = QtWidgets.QPushButton(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSignup.sizePolicy().hasHeightForWidth())
        self.pushButtonSignup.setSizePolicy(sizePolicy)
        self.pushButtonSignup.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonSignup.setFont(font)
        self.pushButtonSignup.setStyleSheet("#Signup { border-image: url(split_grey_background.jpg) 0 0 0 0 stretch stretch;}")
        self.pushButtonSignup.setAutoDefault(False)
        self.pushButtonSignup.setObjectName("pushButtonSignup")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.pushButtonSignup)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButtonBack = QtWidgets.QPushButton(Signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBack.sizePolicy().hasHeightForWidth())
        self.pushButtonBack.setSizePolicy(sizePolicy)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setAutoDefault(False)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.verticalLayout.addWidget(self.pushButtonBack)

        self.retranslateUi(Signup)
        QtCore.QMetaObject.connectSlotsByName(Signup)

    def retranslateUi(self, Signup):
        _translate = QtCore.QCoreApplication.translate
        Signup.setWindowTitle(_translate("Signup", "Inter Planetary Flash Cards"))
        self.labelWelcome.setText(_translate("Signup", "Sign up for IPFC"))
        self.labelTitle.setText(_translate("Signup", "Inter Planetary Flash Cards"))
        self.label.setText(_translate("Signup", "All users must also have a Pinata account.\n"
"Click here to sign up."))
        self.pushButtonPinata.setText(_translate("Signup", "Pinata sign up"))
        self.labelEmail.setText(_translate("Signup", "Email"))
        self.labelPassword.setText(_translate("Signup", "Password"))
        self.labelRepeatPassword.setText(_translate("Signup", "Repeat Password"))
        self.labelPinataAPI.setText(_translate("Signup", "Pinata API key"))
        self.labelPinataKey.setText(_translate("Signup", "Pinata secret key"))
        self.pushButtonSignup.setText(_translate("Signup", "IPFC Sign up"))
        self.pushButtonBack.setText(_translate("Signup", "Back"))
