# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IPFC_login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(380, 480)
        Login.setStyleSheet("#Login { border-image: url(split_grey_background.jpg) 0 0 0 0 stretch stretch;}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelWelcome = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.labelWelcome.setFont(font)
        self.labelWelcome.setObjectName("labelWelcome")
        self.verticalLayout.addWidget(self.labelWelcome)
        self.labelTitle = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        font.setPointSize(20)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 50, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.labelPassword = QtWidgets.QLabel(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPassword.sizePolicy().hasHeightForWidth())
        self.labelPassword.setSizePolicy(sizePolicy)
        self.labelPassword.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.labelPassword.setFont(font)
        self.labelPassword.setAutoFillBackground(False)
        self.labelPassword.setScaledContents(False)
        self.labelPassword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPassword.setIndent(0)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(Login)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditPassword)
        self.labelEmail = QtWidgets.QLabel(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelEmail.sizePolicy().hasHeightForWidth())
        self.labelEmail.setSizePolicy(sizePolicy)
        self.labelEmail.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.labelEmail.setFont(font)
        self.labelEmail.setAutoFillBackground(False)
        self.labelEmail.setScaledContents(False)
        self.labelEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelEmail.setIndent(0)
        self.labelEmail.setObjectName("labelEmail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelEmail)
        self.lineEditEmail = QtWidgets.QLineEdit(Login)
        self.lineEditEmail.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditEmail)
        self.pushButtonSignIn = QtWidgets.QPushButton(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSignIn.sizePolicy().hasHeightForWidth())
        self.pushButtonSignIn.setSizePolicy(sizePolicy)
        self.pushButtonSignIn.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonSignIn.setFont(font)
        self.pushButtonSignIn.setAutoDefault(False)
        self.pushButtonSignIn.setObjectName("pushButtonSignIn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButtonSignIn)
        self.labelResponse = QtWidgets.QLabel(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelResponse.sizePolicy().hasHeightForWidth())
        self.labelResponse.setSizePolicy(sizePolicy)
        self.labelResponse.setText("")
        self.labelResponse.setScaledContents(True)
        self.labelResponse.setWordWrap(True)
        self.labelResponse.setObjectName("labelResponse")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelResponse)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButtonSignUp = QtWidgets.QPushButton(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSignUp.sizePolicy().hasHeightForWidth())
        self.pushButtonSignUp.setSizePolicy(sizePolicy)
        self.pushButtonSignUp.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonSignUp.setFont(font)
        self.pushButtonSignUp.setAutoDefault(False)
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        self.verticalLayout.addWidget(self.pushButtonSignUp)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Inter Planetary Flash Cards"))
        self.labelWelcome.setText(_translate("Login", "Welcome to"))
        self.labelTitle.setText(_translate("Login", "Inter Planetary Flash Cards"))
        self.labelPassword.setText(_translate("Login", "Password"))
        self.labelEmail.setText(_translate("Login", "Email"))
        self.pushButtonSignIn.setText(_translate("Login", "Sign in"))
        self.pushButtonSignUp.setText(_translate("Login", "Sign up"))
