# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IPFC_Quiz_choose2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuizChoose(object):
    def setupUi(self, QuizChoose):
        QuizChoose.setObjectName("QuizChoose")
        QuizChoose.resize(380, 480)
        QuizChoose.setStyleSheet("#QuizChoose { border-image: url(split_grey_background.jpg) 0 0 0 0 stretch stretch;}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(QuizChoose)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSliderQuestNum = QtWidgets.QSlider(QuizChoose)
        self.horizontalSliderQuestNum.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderQuestNum.setObjectName("horizontalSliderQuestNum")
        self.horizontalLayout_2.addWidget(self.horizontalSliderQuestNum)
        self.lineEditQuestNum = QtWidgets.QLineEdit(QuizChoose)
        self.lineEditQuestNum.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEditQuestNum.setObjectName("lineEditQuestNum")
        self.horizontalLayout_2.addWidget(self.lineEditQuestNum)
        self.label_4 = QtWidgets.QLabel(QuizChoose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_2.setStretch(0, 120)
        self.horizontalLayout_2.setStretch(1, 30)
        self.horizontalLayout_2.setStretch(2, 50)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.radioButtonFtoB = QtWidgets.QRadioButton(QuizChoose)
        self.radioButtonFtoB.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.radioButtonFtoB.setFont(font)
        self.radioButtonFtoB.setChecked(True)
        self.radioButtonFtoB.setObjectName("radioButtonFtoB")
        self.verticalLayout.addWidget(self.radioButtonFtoB)
        self.radioButtonBtoF = QtWidgets.QRadioButton(QuizChoose)
        self.radioButtonBtoF.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.radioButtonBtoF.setFont(font)
        self.radioButtonBtoF.setObjectName("radioButtonBtoF")
        self.verticalLayout.addWidget(self.radioButtonBtoF)
        self.frame = QtWidgets.QFrame(QuizChoose)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonSelfReport = QtWidgets.QPushButton(QuizChoose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelfReport.sizePolicy().hasHeightForWidth())
        self.pushButtonSelfReport.setSizePolicy(sizePolicy)
        self.pushButtonSelfReport.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonSelfReport.setFont(font)
        self.pushButtonSelfReport.setAutoDefault(False)
        self.pushButtonSelfReport.setObjectName("pushButtonSelfReport")
        self.gridLayout.addWidget(self.pushButtonSelfReport, 0, 1, 1, 1)
        self.pushButtonWriteAnswer = QtWidgets.QPushButton(QuizChoose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonWriteAnswer.sizePolicy().hasHeightForWidth())
        self.pushButtonWriteAnswer.setSizePolicy(sizePolicy)
        self.pushButtonWriteAnswer.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonWriteAnswer.setFont(font)
        self.pushButtonWriteAnswer.setAutoDefault(False)
        self.pushButtonWriteAnswer.setObjectName("pushButtonWriteAnswer")
        self.gridLayout.addWidget(self.pushButtonWriteAnswer, 1, 1, 1, 1)
        self.pushButtonMultiChoice = QtWidgets.QPushButton(QuizChoose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMultiChoice.sizePolicy().hasHeightForWidth())
        self.pushButtonMultiChoice.setSizePolicy(sizePolicy)
        self.pushButtonMultiChoice.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonMultiChoice.setFont(font)
        self.pushButtonMultiChoice.setAutoDefault(False)
        self.pushButtonMultiChoice.setObjectName("pushButtonMultiChoice")
        self.gridLayout.addWidget(self.pushButtonMultiChoice, 0, 0, 1, 1)
        self.pushButtonTrueFalse = QtWidgets.QPushButton(QuizChoose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTrueFalse.sizePolicy().hasHeightForWidth())
        self.pushButtonTrueFalse.setSizePolicy(sizePolicy)
        self.pushButtonTrueFalse.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonTrueFalse.setFont(font)
        self.pushButtonTrueFalse.setAutoDefault(False)
        self.pushButtonTrueFalse.setObjectName("pushButtonTrueFalse")
        self.gridLayout.addWidget(self.pushButtonTrueFalse, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)

        self.retranslateUi(QuizChoose)
        QtCore.QMetaObject.connectSlotsByName(QuizChoose)

    def retranslateUi(self, QuizChoose):
        _translate = QtCore.QCoreApplication.translate
        QuizChoose.setWindowTitle(_translate("QuizChoose", "Inter Planetary Flash Cards"))
        self.label_4.setText(_translate("QuizChoose", "   Questions"))
        self.radioButtonFtoB.setText(_translate("QuizChoose", "See front, guess back"))
        self.radioButtonBtoF.setText(_translate("QuizChoose", "See back, guess front"))
        self.pushButtonSelfReport.setText(_translate("QuizChoose", "Self Report"))
        self.pushButtonWriteAnswer.setText(_translate("QuizChoose", "Write the Answer"))
        self.pushButtonMultiChoice.setText(_translate("QuizChoose", "Multiple Choice"))
        self.pushButtonTrueFalse.setText(_translate("QuizChoose", "True/False"))
