# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IPFC_Multi_choice.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MultiChoice(object):
    def setupUi(self, MultiChoice):
        MultiChoice.setObjectName("MultiChoice")
        MultiChoice.resize(380, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MultiChoice.sizePolicy().hasHeightForWidth())
        MultiChoice.setSizePolicy(sizePolicy)
        MultiChoice.setStyleSheet("#MultiChoice { border-image: url(split_grey_background.jpg) 0 0 0 0 stretch stretch;}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MultiChoice)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.QLabelCard = QtWidgets.QLabel(MultiChoice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QLabelCard.sizePolicy().hasHeightForWidth())
        self.QLabelCard.setSizePolicy(sizePolicy)
        self.QLabelCard.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(20)
        self.QLabelCard.setFont(font)
        self.QLabelCard.setAutoFillBackground(False)
        self.QLabelCard.setStyleSheet("border-image: url(card_graphic.jpg) 0 0 0 0 stretch stretch")
        self.QLabelCard.setScaledContents(True)
        self.QLabelCard.setAlignment(QtCore.Qt.AlignCenter)
        self.QLabelCard.setWordWrap(True)
        self.QLabelCard.setObjectName("QLabelCard")
        self.verticalLayout_2.addWidget(self.QLabelCard)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget_A = QtWidgets.QWidget(MultiChoice)
        self.horizontalWidget_A.setStyleSheet("#horizontalWidget_5 {border-image: url(/Users/chenlu/PycharmProjects/experiments1/IPFC/PyQT_App/card_graphic_bottom.jpg)}")
        self.horizontalWidget_A.setObjectName("horizontalWidget_A")
        self.horizontalLayoutA = QtWidgets.QHBoxLayout(self.horizontalWidget_A)
        self.horizontalLayoutA.setObjectName("horizontalLayoutA")
        self.QLabelA = QLabel_changed(self.horizontalWidget_A)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QLabelA.sizePolicy().hasHeightForWidth())
        self.QLabelA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        self.QLabelA.setFont(font)
        self.QLabelA.setMouseTracking(True)
        self.QLabelA.setAutoFillBackground(False)
        self.QLabelA.setStyleSheet("background: white")
        self.QLabelA.setScaledContents(True)
        self.QLabelA.setAlignment(QtCore.Qt.AlignCenter)
        self.QLabelA.setWordWrap(True)
        self.QLabelA.setObjectName("QLabelA")
        self.horizontalLayoutA.addWidget(self.QLabelA)
        self.ImgLabelA = QtWidgets.QLabel(self.horizontalWidget_A)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImgLabelA.sizePolicy().hasHeightForWidth())
        self.ImgLabelA.setSizePolicy(sizePolicy)
        self.ImgLabelA.setText("")
        self.ImgLabelA.setObjectName("ImgLabelA")
        self.horizontalLayoutA.addWidget(self.ImgLabelA)
        self.verticalLayout.addWidget(self.horizontalWidget_A)
        self.horizontalWidget_B = QtWidgets.QWidget(MultiChoice)
        self.horizontalWidget_B.setStyleSheet("#horizontalWidget_5 {border-image: url(/Users/chenlu/PycharmProjects/experiments1/IPFC/PyQT_App/card_graphic_bottom.jpg)}")
        self.horizontalWidget_B.setObjectName("horizontalWidget_B")
        self.horizontalLayoutB = QtWidgets.QHBoxLayout(self.horizontalWidget_B)
        self.horizontalLayoutB.setObjectName("horizontalLayoutB")
        self.QLabelB = QLabel_changed(self.horizontalWidget_B)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QLabelB.sizePolicy().hasHeightForWidth())
        self.QLabelB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        self.QLabelB.setFont(font)
        self.QLabelB.setMouseTracking(True)
        self.QLabelB.setAutoFillBackground(False)
        self.QLabelB.setStyleSheet("background: white")
        self.QLabelB.setScaledContents(True)
        self.QLabelB.setAlignment(QtCore.Qt.AlignCenter)
        self.QLabelB.setWordWrap(True)
        self.QLabelB.setObjectName("QLabelB")
        self.horizontalLayoutB.addWidget(self.QLabelB)
        self.ImgLabelB = QtWidgets.QLabel(self.horizontalWidget_B)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImgLabelB.sizePolicy().hasHeightForWidth())
        self.ImgLabelB.setSizePolicy(sizePolicy)
        self.ImgLabelB.setText("")
        self.ImgLabelB.setObjectName("ImgLabelB")
        self.horizontalLayoutB.addWidget(self.ImgLabelB)
        self.verticalLayout.addWidget(self.horizontalWidget_B)
        self.horizontalWidget_C = QtWidgets.QWidget(MultiChoice)
        self.horizontalWidget_C.setStyleSheet("#horizontalWidget_3 {border-image: url(/Users/chenlu/PycharmProjects/experiments1/IPFC/PyQT_App/card_graphic_bottom.jpg)}")
        self.horizontalWidget_C.setObjectName("horizontalWidget_C")
        self.horizontalLayoutC = QtWidgets.QHBoxLayout(self.horizontalWidget_C)
        self.horizontalLayoutC.setObjectName("horizontalLayoutC")
        self.QLabelC = QLabel_changed(self.horizontalWidget_C)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QLabelC.sizePolicy().hasHeightForWidth())
        self.QLabelC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        self.QLabelC.setFont(font)
        self.QLabelC.setMouseTracking(True)
        self.QLabelC.setAutoFillBackground(False)
        self.QLabelC.setStyleSheet("background: white")
        self.QLabelC.setScaledContents(True)
        self.QLabelC.setAlignment(QtCore.Qt.AlignCenter)
        self.QLabelC.setWordWrap(True)
        self.QLabelC.setObjectName("QLabelC")
        self.horizontalLayoutC.addWidget(self.QLabelC)
        self.ImgLabelC = QtWidgets.QLabel(self.horizontalWidget_C)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImgLabelC.sizePolicy().hasHeightForWidth())
        self.ImgLabelC.setSizePolicy(sizePolicy)
        self.ImgLabelC.setText("")
        self.ImgLabelC.setObjectName("ImgLabelC")
        self.horizontalLayoutC.addWidget(self.ImgLabelC)
        self.verticalLayout.addWidget(self.horizontalWidget_C)
        self.horizontalWidget_D = QtWidgets.QWidget(MultiChoice)
        self.horizontalWidget_D.setStyleSheet("#horizontalWidget_4 {border-image: url(/Users/chenlu/PycharmProjects/experiments1/IPFC/PyQT_App/card_graphic_bottom.jpg)}")
        self.horizontalWidget_D.setObjectName("horizontalWidget_D")
        self.horizontalLayoutD = QtWidgets.QHBoxLayout(self.horizontalWidget_D)
        self.horizontalLayoutD.setObjectName("horizontalLayoutD")
        self.QLabelD = QLabel_changed(self.horizontalWidget_D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QLabelD.sizePolicy().hasHeightForWidth())
        self.QLabelD.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        self.QLabelD.setFont(font)
        self.QLabelD.setMouseTracking(True)
        self.QLabelD.setAutoFillBackground(False)
        self.QLabelD.setStyleSheet("background: white")
        self.QLabelD.setScaledContents(True)
        self.QLabelD.setAlignment(QtCore.Qt.AlignCenter)
        self.QLabelD.setWordWrap(True)
        self.QLabelD.setObjectName("QLabelD")
        self.horizontalLayoutD.addWidget(self.QLabelD)
        self.ImgLabelD = QtWidgets.QLabel(self.horizontalWidget_D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImgLabelD.sizePolicy().hasHeightForWidth())
        self.ImgLabelD.setSizePolicy(sizePolicy)
        self.ImgLabelD.setText("")
        self.ImgLabelD.setObjectName("ImgLabelD")
        self.horizontalLayoutD.addWidget(self.ImgLabelD)
        self.verticalLayout.addWidget(self.horizontalWidget_D)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.QlabelCorrect = QtWidgets.QLabel(MultiChoice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QlabelCorrect.sizePolicy().hasHeightForWidth())
        self.QlabelCorrect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.QlabelCorrect.setFont(font)
        self.QlabelCorrect.setText("")
        self.QlabelCorrect.setWordWrap(True)
        self.QlabelCorrect.setObjectName("QlabelCorrect")
        self.horizontalLayout.addWidget(self.QlabelCorrect)
        self.pushButtonNext = QtWidgets.QPushButton(MultiChoice)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.pushButtonNext.setFont(font)
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.horizontalLayout.addWidget(self.pushButtonNext)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(MultiChoice)
        QtCore.QMetaObject.connectSlotsByName(MultiChoice)

    def retranslateUi(self, MultiChoice):
        _translate = QtCore.QCoreApplication.translate
        MultiChoice.setWindowTitle(_translate("MultiChoice", "Inter Planetary Flash Cards"))
        self.QLabelCard.setText(_translate("MultiChoice", "Text"))
        self.QLabelA.setText(_translate("MultiChoice", "TextLabel"))
        self.QLabelB.setText(_translate("MultiChoice", "TextLabel"))
        self.QLabelC.setText(_translate("MultiChoice", "TextLabel"))
        self.QLabelD.setText(_translate("MultiChoice", "TextLabel"))
        self.pushButtonNext.setText(_translate("MultiChoice", "Next"))
from qlabel2 import QLabel_changed


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MultiChoice = QtWidgets.QDialog()
    ui = Ui_MultiChoice()
    ui.setupUi(MultiChoice)
    MultiChoice.show()
    sys.exit(app.exec_())
